# 定义输入时钟：周期为 20ns (对应 50MHz)
create_clock -period 20.000 -name sys_clk [get_ports sys_clk]

set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports capture_pin]
set_property PACKAGE_PIN U20 [get_ports capture_pin]
set_property PACKAGE_PIN U18 [get_ports sys_clk]
set_property PACKAGE_PIN N16 [get_ports rst_n]

create_generated_clock -name clk_3m2 -source [get_pins u_clk_gen/clk_out1] -divide_by 10 [get_pins clk_3m2_reg_reg/Q]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_32m]

set_property PACKAGE_PIN U13 [get_ports DA_Clk]
set_property PACKAGE_PIN W15 [get_ports {DA_Data[7]}]
set_property PACKAGE_PIN V15 [get_ports {DA_Data[6]}]
set_property PACKAGE_PIN Y14 [get_ports {DA_Data[5]}]
set_property PACKAGE_PIN W14 [get_ports {DA_Data[4]}]
set_property PACKAGE_PIN W13 [get_ports {DA_Data[3]}]
set_property PACKAGE_PIN V12 [get_ports {DA_Data[2]}]
set_property PACKAGE_PIN U15 [get_ports {DA_Data[1]}]
set_property PACKAGE_PIN U14 [get_ports {DA_Data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports DA_Clk]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_Data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_Data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_Data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_Data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_Data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_Data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_Data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_Data[0]}]
